#!/usr/bin/env zsh

# Cache Brew prefix and repo because they take forever (thanks alyssa)
BREW_PREFIX="$(brew --prefix)"
BREW_REPO="$(brew --repo)"

autoload -Uz colors && colors

source "$BREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$BREW_PREFIX/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "$BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Liquid Prompt
source "$BREW_PREFIX/opt/liquidprompt/share/liquidprompt"